### ISSUE TITLE
Package downgrade detected.

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/CosmosFtp#1]
[error NU1605: Detected package downgrade: Cosmos.System2 from 0.1.0-localbuild20220525025937 to 0.1.0-localbuild. Reference the package directly from the project to select a different version. 
](https://github.com/aura-systems/Aura-Operating-System/runs/6762135870)

**Comment by quajak** [comment]
Removing the version here https://github.com/CosmosOS/CosmosFtp/blob/698a99734a52ae3a28e49c89c96e9be6405e484a/CosmosFtpServer.csproj#L25 might help. But I think the real solution would be to actually release nuget packages with the userkits which

**Comment by quajak** [comment]
Is it still happening?
