### ISSUE TITLE
How do i use?

### ISSUE THREAD

**Issue by CSharpChase** [CosmosOS/CosmosFtp#3]
How do I use, Does it come with its own client or do i need to provide one, If i need to provide one how do i get the ip of the current machine?

**Comment by valentinbreiz** [comment]
Hello, this project is not a FTP client, it's a server. You can find more information about how to connect using a remote computer in the cosmos documentation (https://cosmosos.github.io/articles/Kernel/Network.html#ftp).

**Comment by CSharpChase** [comment]
Thank you good sir.
